const express = require('express')
const app= express()
const routes = require('./routes/index')
const cors = require('cors')
app.use(cors())
require('dotenv').config()
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use('/public', express.static('public'))
routes(app)
const PORT = process.env.PORT ? process.env.PORT : 5000 
app.listen(PORT, () => console.log("server connect to port : ", PORT))